会場を株式会社インプレイスに更新した
katsuyuki-hori/ichiyasaGitSample pull request #1
Opened 2023-05-05 21:56 UTC by katsuyuki-hori

### 変更内容
イベント開催会場を「株式会社インプレイス」に更新しました。

### 背景
「株式会社インプレイス」さんがイベント会場を提供してくださることになりました。

2023-05-05 22:15 UTC, q-hori commented
修正ありがとうございます。問題ないのでマージします。

2023-05-06 07:36 UTC, q-hori requested changes
修正ありがとうございます。指摘の確認と修正をお願いします。

2023-05-06 07:36 UTC, q-hori commented on index.html
> +                        <p>株式会社インプレイス  イベントセミナー会場</p>
「インプレイス」ではなく「インプレス」です。

2023-05-06 07:44 UTC, katsuyuki-hori commented on index.html
> +                        <p>株式会社インプレイス  イベントセミナー会場</p>
修正したものをプッシュしたので、再度ご確認ください。

2023-05-06 07:45 UTC, q-hori commented on index.html
> +                        <p>株式会社インプレイス  イベントセミナー会場</p>
ありがとうございます。

2023-05-06 07:46 UTC, q-hori approved these changes

2023-05-06 08:09 UTC, merged